steps:
  # Build de la imagen Docker desde el directorio backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-final-backend:$BUILD_ID', './backend']
    
  # Push de la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-final-backend:$BUILD_ID']
    
  # Deploy a Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'proyecto-final-backend'
      - '--image=gcr.io/$PROJECT_ID/proyecto-final-backend:$BUILD_ID'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--set-env-vars=SPRING_PROFILES_ACTIVE=firebase'

# Configuración de imágenes
images:
  - 'gcr.io/$PROJECT_ID/proyecto-final-backend:$BUILD_ID'

# Configuración de opciones
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8' 