steps:
  # Construir imagen Docker (desde el directorio backend)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proyecto-final-backend:$BUILD_ID', './backend']
  
  # Subir imagen a Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proyecto-final-backend:$BUILD_ID']
  
  # Desplegar en Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'proyecto-final-backend'
      - '--image=gcr.io/$PROJECT_ID/proyecto-final-backend:$BUILD_ID'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--set-env-vars=SPRING_PROFILES_ACTIVE=firebase'
      - '--set-secrets=MONGODB_URI=mongodb-uri:latest,JWT_SECRET=jwt-secret:latest'

# Imágenes que se construyen
images:
  - 'gcr.io/$PROJECT_ID/proyecto-final-backend:$BUILD_ID'

# Configuración adicional
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout
timeout: 1200s 