name: Trigger Local Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'cloudbuild.yaml'

jobs:
  notify-local-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Local Machine
        run: |
          echo "🚀 Backend changes detected in commit ${{ github.sha }}"
          echo "📧 Sending notification to trigger local deploy..."
          
          # Webhook a tu máquina local (opcional)
          # curl -X POST "http://tu-ip-publica:8080/webhook/deploy" \
          #   -H "Content-Type: application/json" \
          #   -d '{"commit": "${{ github.sha }}", "branch": "${{ github.ref_name }}"}'
          
          echo "✅ Notification sent. Please run local deploy manually."
          echo "Command: gcloud builds submit --config=cloudbuild-local.yaml ." 